<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AnbuPC" failures="6" tests="40" name="Default test" time="14.959" errors="0" timestamp="2024-11-25T00:07:03 EST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="3.453"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.746"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.258"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.265"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.269"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.44"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.196"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.204"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.362"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.233"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.195"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.593"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.288"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.209"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.177"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.228"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.203">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.Request.BatchModuleRequest.getBybatchIDValidation(BatchModuleRequest.java:240)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_body_get_by_batch_id(BatchModuleSteps.java:74)
at ✽.Admin receives status code with response body GetBy BatchID "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:46)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.236"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.173"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.173"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.198"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.233"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.206">
    <failure type="java.lang.AssertionError" message="expected [BatTest34] but found [Batch29Test]">
      <![CDATA[java.lang.AssertionError: expected [BatTest34] but found [Batch29Test]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at api.Request.BatchModuleRequest.getByBatchName_MessageValidation(BatchModuleRequest.java:271)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_body_get_by_batch_name(BatchModuleSteps.java:96)
at ✽.Admin receives status code with response body GetBy BatchName "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:64)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.189"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.193"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.199"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.217">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;[16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401]&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "[16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401, 16401]"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at java_lang_Integer$parseInt.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.common.path.ObjectConverter.convertObjectTo(ObjectConverter.groovy:29)
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:245)
at api.Request.BatchModuleRequest.getBatchByProgramIDvalidation(BatchModuleRequest.java:230)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_body_get_by_program_id(BatchModuleSteps.java:114)
at ✽.Admin receives status code with response body GetBy ProgramID "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.204">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.Request.BatchModuleRequest.getBatchByProgramIDvalidation(BatchModuleRequest.java:222)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_body_get_by_program_id(BatchModuleSteps.java:114)
at ✽.Admin receives status code with response body GetBy ProgramID "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:81)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.171"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.162"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.177"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.169"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.176"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.159"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.251"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.186"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.183"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.156"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.235">
    <failure type="java.lang.AssertionError" message="expected [8722] but found [8671]">
      <![CDATA[java.lang.AssertionError: expected [8722] but found [8671]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1459)
at api.Request.BatchModuleRequest.updateBybatchIdValidation(BatchModuleRequest.java:156)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_message_for_update_by_batch_id_request(BatchModuleSteps.java:151)
at ✽.Admin receives status code with response message for UpdateByBatchID request "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:113)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.171">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.Request.BatchModuleRequest.updateBybatchIdValidation(BatchModuleRequest.java:148)
at api.StepDefinitions.BatchModuleSteps.admin_receives_status_code_with_response_message_for_update_by_batch_id_request(BatchModuleSteps.java:151)
at ✽.Admin receives status code with response message for UpdateByBatchID request "200"(file:///C:/Users/anbum/OneDrive/Desktop/Anbu/LMS_Phase2_RestAssured/LMS_GIT/Team04_APIAvengers_LMSHackathon/src/test/resources/features/03batchModule/batchModule.feature:113)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
