<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Mahesh_PC" failures="34" tests="37" name="Default test" time="8.544" errors="0" timestamp="2024-11-24T22:10:53 CST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.607">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.ss.usermodel.Sheet.getLastRowNum()&amp;quot; because &amp;quot;sheet&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.136">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.ss.usermodel.Sheet.getLastRowNum()&amp;quot; because &amp;quot;sheet&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.149">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.ss.usermodel.Sheet.getLastRowNum()&amp;quot; because &amp;quot;sheet&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="2.343">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.Request.CreateProgramRequest.sendPostRequest(CreateProgramRequest.java:108)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_post_request_to_create_a_program(ProgramCreateSteps.java:78)
at ✽.Admin sends POST request to create a program for "POST_PROGRAM_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/01programCreate.feature:7)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.Request.CreateProgramRequest.sendPostRequest(CreateProgramRequest.java:108)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_post_request_to_create_a_program(ProgramCreateSteps.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:62)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:81)
at io.cucumber.core.runner.TestStep.run(TestStep.java:53)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:135)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.184">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.poi.ss.usermodel.Sheet.getLastRowNum()&amp;quot; because &amp;quot;sheet&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:6)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.136">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_TC11"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.016">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_12"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.041">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_13"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.454"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.01">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_15"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.013">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_16"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.029">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_17"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.023">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.GetAllProgramRequest.sendGetRequest(GetAllProgramRequest.java:47)
at api.StepDefinitions.GetAllProgramsStep.adminSendsGETRequestWithEndpointFor(GetAllProgramsStep.java:32)
at ✽.Admin sends GET request with endpoint for "GET_ID_PROGRAM_18"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.014">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_19"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.01">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_20"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.018">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_21"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.016">
    <failure type="java.lang.IllegalArgumentException" message="accessToken cannot be null">
      <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_22"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.249"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.096">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.076">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 1 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 1 with valid request body for "PUT_PROGRAM_02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.038">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.028">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_04"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.051">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_06"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.06">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_07"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.303">
    <failure type="java.lang.AssertionError" message="Expected status code does not match actual status code. expected [404] but found [401]">
      <![CDATA[java.lang.AssertionError: Expected status code does not match actual status code. expected [404] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:233)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.339"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.045">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 0 by Program ID for "PUT_PROGRAM_ID_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.06">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 1 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 1 by Program ID for "PUT_PROGRAM_ID_02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.058">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 0 by Program ID for "PUT_PROGRAM_ID_03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.048">
    <failure type="java.lang.AssertionError" message="Expected status code 404, but no response was received.">
      <![CDATA[java.lang.AssertionError: Expected status code 404, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.347">
    <failure type="java.lang.AssertionError" message="Expected status code does not match actual status code. expected [404] but found [401]">
      <![CDATA[java.lang.AssertionError: Expected status code does not match actual status code. expected [404] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:233)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.073">
    <failure type="java.lang.AssertionError" message="Expected status code 400, but no response was received.">
      <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.149">
    <failure type="java.lang.AssertionError" message="Expected status code 400, but no response was received.">
      <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.094">
    <failure type="java.lang.AssertionError" message="Expected status code 400, but no response was received.">
      <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.036">
    <failure type="java.lang.AssertionError" message="Expected status code 401, but no response was received.">
      <![CDATA[java.lang.AssertionError: Expected status code 401, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "401"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.063">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByIDInvalidMethod(CreateProgramRequest.java:324)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_invalidMethod(ProgramCreateSteps.java:220)
at ✽.Admin sends PUT request for 0 with invalid method for "PUT_PROGRAM_ID_10"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:73)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="0.032">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.DeleteProgramRequest.deleteProgramByIDReq(DeleteProgramRequest.java:82)
at api.StepDefinitions.DeleteProgramSteps.admin_sends_delete_request_for_with_program_id_and_valid_endpoint_for(DeleteProgramSteps.java:57)
at ✽.Admin sends DELETE request for 0 with programID and valid endpoint for "DEL_PROGRAM_ID_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/04programDelete.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
