<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="37" passed="3" failed="34" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-24T22:10:45 CST" name="Default suite" finished-at="2024-11-24T22:10:53 CST" duration-ms="8544">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-11-24T22:10:45 CST" name="Default test" finished-at="2024-11-24T22:10:53 CST" duration-ms="8544">
      <class name="api.TestRunner.TestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:45 CST" name="setUpClass" finished-at="2024-11-24T22:10:46 CST" duration-ms="923" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6d946eee]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:46 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:48 CST" duration-ms="1607" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User Login valid credential"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["User Login Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:48 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:48 CST" duration-ms="136" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User Login valid credential"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["User Login Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:48 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:48 CST" duration-ms="149" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User Login valid credential"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["User Login Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/01userLogin/userLogin.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:48 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:50 CST" duration-ms="2343" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for creating a program"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Create Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="io.restassured.path.json.exception.JsonPathException">
            <message>
              <![CDATA[Failed to parse the JSON document]]>
            </message>
            <full-stacktrace>
              <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.Request.CreateProgramRequest.sendPostRequest(CreateProgramRequest.java:108)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_post_request_to_create_a_program(ProgramCreateSteps.java:78)
at ✽.Admin sends POST request to create a program for "POST_PROGRAM_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/01programCreate.feature:7)
Caused by: java.lang.IllegalArgumentException: The JSON input text should neither be null nor empty.
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:80)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at io.restassured.path.json.JsonPath.getString(JsonPath.java:352)
at api.Request.CreateProgramRequest.sendPostRequest(CreateProgramRequest.java:108)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_post_request_to_create_a_program(ProgramCreateSteps.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
at io.cucumber.java.Invoker.invoke(Invoker.java:24)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:62)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:81)
at io.cucumber.core.runner.TestStep.run(TestStep.java:53)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:135)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- io.restassured.path.json.exception.JsonPathException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:50 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:50 CST" duration-ms="184" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User Login valid credential"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Sheet.getLastRowNum()" because "sheet" is null
at api.Utility.ExcelReader.readTestDataLoginLogout(ExcelReader.java:57)
at api.Request.UserLogInOutRequest.loadTestData(UserLogInOutRequest.java:71)
at api.StepDefinitions.UserLogInOutSteps.adminCreatesPOSTLoginRequestBodyFor(UserLogInOutSteps.java:21)
at ✽.Admin creates POST login request body for "POST_LOGIN-01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:6)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:50 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:50 CST" duration-ms="136" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:53)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:217)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:240)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_TC11"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:50 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:50 CST" duration-ms="16" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_12"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:50 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="41" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALL_PROGRAM_13"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="454" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="10" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_15"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="13" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_16"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="29" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_17"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="23" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.GetAllProgramRequest.sendGetRequest(GetAllProgramRequest.java:47)
at api.StepDefinitions.GetAllProgramsStep.adminSendsGETRequestWithEndpointFor(GetAllProgramsStep.java:32)
at ✽.Admin sends GET request with endpoint for "GET_ID_PROGRAM_18"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="14" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ID_PROGRAM_19"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="10" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_20"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="18" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_21"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="16" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[accessToken cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: accessToken cannot be null
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:60)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:86)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.common.assertion.AssertParameter.notNull(AssertParameter.groovy:26)
at io.restassured.internal.common.assertion.AssertParameter$notNull.callStatic(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:158)
at io.restassured.specification.AuthenticationSpecification$oauth2.callCurrent(Unknown Source)
at io.restassured.internal.AuthenticationSpecificationImpl.oauth2(AuthenticationSpecificationImpl.groovy:151)
at api.Request.GetAllProgramRequest.buildRequest(GetAllProgramRequest.java:30)
at api.StepDefinitions.GetAllProgramsStep.adminCreatesGETProgramRequestForTheLMSAPIFor(GetAllProgramsStep.java:27)
at ✽.Admin creates GET Program request for the LMS API for "GET_ALLUSERS_PROGRAM_22"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/02programsGet.feature:26)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="249" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["User able to retrieve all programs with valid Endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Get All Programs"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:51 CST" duration-ms="96" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:51 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="76" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 1 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 1 with valid request body for "PUT_PROGRAM_02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="38" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="28" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_04"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="51" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_06"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="60" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with valid request body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequest(CreateProgramRequest.java:183)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_to_create_a_program(ProgramCreateSteps.java:182)
at ✽.Admin sends PUT request for 0 with valid request body for "PUT_PROGRAM_07"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="303" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with invalid Program Name"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code does not match actual status code. expected [404] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code does not match actual status code. expected [404] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:233)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:24)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="339" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program with No Auth"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="45" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 0 by Program ID for "PUT_PROGRAM_ID_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:52 CST" duration-ms="60" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 1 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 1 by Program ID for "PUT_PROGRAM_ID_02"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:52 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="58" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByID(CreateProgramRequest.java:249)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_byProgId(ProgramCreateSteps.java:202)
at ✽.Admin sends PUT request for 0 by Program ID for "PUT_PROGRAM_ID_03"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:44)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="48" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 404, but no response was received.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 404, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="347" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code does not match actual status code. expected [404] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code does not match actual status code. expected [404] but found [401]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:233)
at ✽.Response status code should be "404"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="73" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400, but no response was received.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="149" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400, but no response was received.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="94" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 400, but no response was received.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 400, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "400"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="36" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid body"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected status code 401, but no response was received.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected status code 401, but no response was received.
at org.testng.Assert.fail(Assert.java:111)
at api.StepDefinitions.ProgramCreateSteps.response_status_code_should_be(ProgramCreateSteps.java:230)
at ✽.Response status code should be "401"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="63" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Validate API response for updating program by ID with invalid Method"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Update Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.CreateProgramRequest.sendPUTRequestByIDInvalidMethod(CreateProgramRequest.java:324)
at api.StepDefinitions.ProgramCreateSteps.admin_sends_put_request_invalidMethod(ProgramCreateSteps.java:220)
at ✽.Admin sends PUT request for 0 with invalid method for "PUT_PROGRAM_ID_10"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/03programUpdate.feature:73)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-11-24T22:10:53 CST" duration-ms="32" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Delete program by ID with valid endpoint"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Delete Program Module"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 0 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:365)
at java.base/java.util.ArrayList.get(ArrayList.java:428)
at api.Request.DeleteProgramRequest.deleteProgramByIDReq(DeleteProgramRequest.java:82)
at api.StepDefinitions.DeleteProgramSteps.admin_sends_delete_request_for_with_program_id_and_valid_endpoint_for(DeleteProgramSteps.java:57)
at ✽.Admin sends DELETE request for 0 with programID and valid endpoint for "DEL_PROGRAM_ID_01"(file:///C:/Users/manal_/git/Team04_APIAvengers_LMSHackathon/src/test/resources/features/02programModule/04programDelete.feature:8)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:api.TestRunner.TestRunner@3af9c5b7]" started-at="2024-11-24T22:10:53 CST" name="tearDownClass" finished-at="2024-11-24T22:10:53 CST" duration-ms="36" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- api.TestRunner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
